# Generated by Django 2.0.7 on 2018-09-07 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KbMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10, unique=True)),
                ('klaversion', models.CharField(blank=True, max_length=50)),
                ('calcbase', models.CharField(blank=True, max_length=10)),
                ('contractbase', models.CharField(blank=True, max_length=10)),
                ('quotno', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=100)),
                ('datecalc', models.DateField(default='1999-09-09')),
                ('dateupload', models.DateTimeField(default='1999-09-09')),
                ('projname', models.CharField(blank=True, max_length=100)),
                ('customer', models.CharField(blank=True, max_length=100)),
                ('endcustomer', models.CharField(blank=True, max_length=100)),
                ('phase', models.CharField(blank=True, max_length=50)),
                ('aprice', models.FloatField(blank=True, null=True)),
                ('kbsumme', models.BooleanField()),
                ('pbb', models.BooleanField()),
                ('stckliste', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pbb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_business', models.CharField(max_length=150)),
                ('entity', models.CharField(max_length=20, null=True)),
                ('escalation', models.FloatField(null=True)),
                ('transportation', models.FloatField(null=True)),
                ('custom_tax', models.FloatField(null=True)),
                ('fx_gain_loss', models.FloatField(null=True)),
                ('financing', models.FloatField(null=True)),
                ('insurance', models.FloatField(null=True)),
                ('bank_charges', models.FloatField(null=True)),
                ('technical_risk', models.FloatField(null=True)),
                ('warranty', models.FloatField(null=True)),
                ('sales_oh', models.FloatField(null=True)),
                ('net_margin', models.FloatField(null=True)),
                ('single_cost_euro', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('price_nego', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PbbMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_no', models.IntegerField(null=True, unique=True)),
                ('country_inst', models.CharField(blank=True, max_length=100)),
                ('planttype', models.CharField(blank=True, max_length=50)),
                ('projname', models.CharField(blank=True, max_length=100)),
                ('qty_units', models.IntegerField(null=True)),
                ('total_output', models.FloatField(null=True)),
                ('customer', models.CharField(blank=True, max_length=100)),
                ('endcustomer', models.CharField(blank=True, max_length=100)),
                ('bidmanager', models.CharField(blank=True, max_length=100)),
                ('fx_rate', models.FloatField(null=True)),
                ('total_surcharges', models.FloatField(null=True)),
                ('total_includings', models.FloatField(null=True)),
                ('total_sm', models.FloatField(null=True)),
                ('total_cost', models.FloatField(null=True)),
                ('total_price_euro', models.FloatField(null=True)),
                ('total_price_fx', models.FloatField(null=True)),
                ('kbmeta', models.ForeignKey(db_column='kbmeta', on_delete=django.db.models.deletion.CASCADE, to='kbsumme.KbMeta', to_field='pid')),
            ],
        ),
        migrations.CreateModel(
            name='Posd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgpos', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=200)),
                ('hours', models.CharField(max_length=5)),
                ('cost', models.CharField(max_length=5)),
                ('pd_hours', models.IntegerField(null=True)),
                ('pd_cost', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stueckliste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, max_length=50)),
                ('sheet', models.CharField(blank=True, max_length=50)),
                ('caname', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('mlfb', models.CharField(blank=True, max_length=100)),
                ('qty', models.FloatField()),
                ('single_cost', models.FloatField()),
                ('typlical', models.CharField(blank=True, max_length=50)),
                ('total_cost', models.FloatField()),
                ('kbmeta', models.ForeignKey(db_column='kbmeta', on_delete=django.db.models.deletion.CASCADE, to='kbsumme.KbMeta', to_field='pid')),
            ],
        ),
        migrations.CreateModel(
            name='T3000db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField()),
                ('cost', models.FloatField()),
                ('kbmeta', models.ForeignKey(db_column='kbmeta', on_delete=django.db.models.deletion.CASCADE, to='kbsumme.KbMeta', to_field='pid')),
                ('posd', models.ForeignKey(db_column='posd', on_delete=django.db.models.deletion.CASCADE, to='kbsumme.Posd', to_field='hgpos')),
            ],
        ),
        migrations.AddField(
            model_name='pbb',
            name='pbbmeta',
            field=models.ForeignKey(db_column='pbbmeta', on_delete=django.db.models.deletion.CASCADE, to='kbsumme.PbbMeta', to_field='offer_no'),
        ),
    ]
