# Generated by Django 2.0.7 on 2018-07-23 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KbMeta',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('klaversion', models.CharField(blank=True, max_length=50)),
                ('calcbase', models.CharField(blank=True, max_length=10)),
                ('contractbase', models.CharField(blank=True, max_length=10)),
                ('quotno', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=100)),
                ('datecalc', models.DateField(default='1999-09-09')),
                ('dateupload', models.DateTimeField(default='1999-09-09')),
                ('projname', models.CharField(blank=True, max_length=100)),
                ('customer', models.CharField(blank=True, max_length=100)),
                ('endcustomer', models.CharField(blank=True, max_length=100)),
                ('phase', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Posd',
            fields=[
                ('id', models.IntegerField()),
                ('hgpos', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('hours', models.CharField(max_length=5)),
                ('cost', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='T3000db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField()),
                ('cost', models.FloatField()),
                ('hgpos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbsumme.Posd')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbsumme.KbMeta')),
            ],
        ),
    ]
