# Generated by Django 2.0.7 on 2018-07-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbsumme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbmeta',
            name='dateupload',
            field=models.DateTimeField(default='1999-09-09'),
        ),
    ]
