# Generated by Django 2.0.7 on 2018-07-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbsumme', '0002_kbmeta_dateupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbmeta',
            name='calcbase',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='kbmeta',
            name='contractbase',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='kbmeta',
            name='customer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kbmeta',
            name='endcustomer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kbmeta',
            name='klaversion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='kbmeta',
            name='projname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
