# Generated by Django 2.0.7 on 2018-07-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbsumme', '0002_stueckliste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stueckliste',
            name='description',
            field=models.TextField(),
        ),
    ]
