# Generated by Django 2.0.7 on 2018-07-22 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbsumme', '0003_auto_20180719_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbmeta',
            name='phase',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='t3000db',
            name='kbmeta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kbsumme.KbMeta'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='t3000db',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='t3000db',
            name='pid',
        ),
    ]
