# Generated by Django 2.0.7 on 2018-08-01 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbsumme', '0003_auto_20180725_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pbb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_business', models.CharField(max_length=150)),
                ('entity', models.CharField(blank=True, max_length=20)),
                ('escalation', models.FloatField()),
                ('transportation', models.FloatField()),
                ('custom_tax', models.FloatField()),
                ('fx_gain_loss', models.FloatField()),
                ('financing', models.FloatField()),
                ('insurance', models.FloatField()),
                ('bank_charges', models.FloatField()),
                ('technical_risk', models.FloatField()),
                ('warranty', models.FloatField()),
                ('sales_oh', models.FloatField()),
                ('net_margin', models.FloatField()),
                ('single_cost_euro', models.FloatField()),
                ('price', models.FloatField()),
                ('price_nego', models.FloatField()),
                ('total_surcharges', models.FloatField()),
                ('total_includings', models.FloatField()),
                ('total_sm', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('total_price_euro', models.FloatField()),
                ('total_price_fx', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PbbMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_no', models.IntegerField(unique=True)),
                ('country_inst', models.CharField(blank=True, max_length=100)),
                ('planttype', models.CharField(blank=True, max_length=50)),
                ('projname', models.CharField(blank=True, max_length=100)),
                ('qty_units', models.IntegerField()),
                ('total_output', models.FloatField()),
                ('customer', models.CharField(blank=True, max_length=100)),
                ('endcustomer', models.CharField(blank=True, max_length=100)),
                ('bidmanager', models.CharField(blank=True, max_length=100)),
                ('fx_rate', models.FloatField()),
                ('kbmeta', models.ForeignKey(db_column='kbmeta', on_delete=django.db.models.deletion.CASCADE, to='kbsumme.KbMeta', to_field='pid')),
            ],
        ),
        migrations.AddField(
            model_name='pbb',
            name='pbbmeta',
            field=models.ForeignKey(db_column='pbbmeta', on_delete=django.db.models.deletion.CASCADE, to='kbsumme.PbbMeta', to_field='offer_no'),
        ),
    ]
