# Generated by Django 2.0.7 on 2018-08-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbsumme', '0005_auto_20180801_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbb',
            name='entity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
